### ISSUE TITLE
Implement initial checks of various services required for a successful off ramp flow

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/vortex#120]
### Context
There are several known reason due to which the offramping transaction using teh Vortex prototype, could fail. Therefore, it makes sense to implement a set of checks when a user lands on the app, such that if any of them fail, the user is unable to initiate the off ramping transaction.

### Requirements

1. Implement the following checks before the UI loads

- [x] Signer-service status: Confirms that both funding accounts have enough funds (the Pendulum funding account requires PEN, USDCaxl and EURC (Circle)).
- [x] Moonbeam status: Confirms that the Moonbeam executor account has sufficient funds and that the service itself works
- [x] Squidrouter status: Confirms that a subset of possible tokens the user can select to see if the app is returning any routes for bridging.
- [x] AMM pool status: Confirms if the AMM / DEX has enough liquidity for the swap transaction to be successful.
- [x] Spacewalk vault status: Confirms that the number of redeemable tokens with a single vault is larger than or equal to the amount to be offramped

2. Implement the following message / screen for the user in case any of the checks fail.

- [ ] TBC

If any of these checks where to fail, we know that the offramp will also fail, so it might be better to disable it until everything is ready. This check can be done upon loading the application and disabling the offramp button.

**Comment by prayagd** [comment]
> Implement the following message / screen for the user in case any of the checks fail.


@pendulum-chain/devs What is the message we show here is the checks fail or should i create a ticket to implement that

**Comment by ebma** [comment]
It shows

> Application initialization failed. Please reload, or try again later if the problem persists.



<img width="699" alt="image" src="https://github.com/user-attachments/assets/54fbe5cc-24e1-4cb7-a6f9-48b2b76dec0a">
