### ISSUE TITLE
Integrate additional events into google analytics query into the prototype

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/vortex#140]
#### Context

The goal is to implement event tracking for user interactions on the Vortex PMF prototype using Google Tag Manager (GTM) and Google Analytics. The provided code template listens for specific user actions (like clicks) and pushes events to the GTM dataLayer. These events will help track user behavior for analysis in Google Analytics. We are still missing 3 events (listed in the requirements) for funnel monitoring.

Code template to create and push events to the data layer for the specified list of events was provided:

```
document.getElementByID("ID").addEventListener('click', function(){
    dataLayer.push({
      'event': 'eventName', //such as select_vault_manually
      'label': 'vaultID', // use actual vaultID
  });
})
```
Please refer to the [ticket](https://app.zenhub.com/workspaces/pendulum-6408a0365cda59c57d39bee5/issues/gh/pendulum-chain/vortex/46)

#### Requirements
- [ ] Add below type of events to the data layer: 
- Change network to Polygon prompt
- Connected wallet address

**Comment by prayagd** [comment]
@vadaynujra should we merge this and #198 ticket?

**Comment by vadaynujra** [comment]
@prayagd @ebma from the events requested in this ticket, the ones yet to be implemented are:
- Connected wallet address
- Prompt for changing network
Shall we update this ticket to only include these two and make it ready?

**Comment by ebma** [comment]
Yes, please do.

**Comment by prayagd** [comment]
> Shall we update this ticket to only include these two and make it ready?

Had added the first will add the second too
