### ISSUE TITLE
Integrate ARS/Anclap into the offramp flow

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/vortex#172]
## Context 
This ticket enables ARS offramps.

## TODO
* Add ARS to the currency dropdown on the withdraw page, icon linked below
* Extend the SEP-24 fee logic to allow for a relative and fixed fee
  * define the proper fee parameters for ARS offramps: 2% relative fee and 10 ARS fixed fee
* When user selects ARS as offramping currency and agrees to the quote
* Add ARS as an output currency and define the output token configuration accordingly
* Implement the Anclap anchor UI when the user selects ARS to offramp
* Introduce a SEP-10 master account secret configuration for the signer service
  * Use the corresponding account as the source account for SEP-10 when Anclap is used as the anchor
  * In that case securely add the SEP-10 signature on the backend

## Notes
* TOML file: https://api.anclap.com/.well-known/stellar.toml 

## Notes
ARS icon - https://static.anclap.com/coin/ars.png

**Comment by gianfra-t** [comment]
@pendulum-chain/product can this be worked already?

**Comment by prayagd** [comment]
> @pendulum-chain/product can this be worked already?

I will get this ready and estimated till then

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/vortex/172?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by gianfra-t** [comment]
I'll assign myself to this since I can test the flow with my bank.

**Comment by TorstenStueber** [comment]
Just want to point out that ARS is not available yet on the AMM. But this should not be a blocker for this ticket here.

**Comment by gianfra-t** [comment]
Yes @TorstenStueber thanks. Since the changes are very small, I'll wait for `ARS` to be "ready" to work on this and test an off-ramp.

**Comment by TorstenStueber** [comment]
@gianfra-t FYI, this has been unblocked now as ARS is now available on Nabla: https://github.com/pendulum-chain/tasks/issues/401#issuecomment-2412361777

**Comment by prayagd** [comment]
@gianfra-t if and when you are unblocked for testing. please record the entire flow and share the recording

**Comment by prayagd** [comment]
Should we close this ticket? the linked PR is outdated

**Comment by TorstenStueber** [comment]
Yes, can be closed.
