### ISSUE TITLE
Enable ARS on vortex UI

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/vortex#173]
## Context
This is a single ticket for all the UI changes to be done for the ARS offramp on the Vortex UI

## Requirements
* Add ARS to the currency dropdown on the withdraw page, icon linked below
* Update the offramp fee to 2% when the user selects ARS in the dropdown
* Set a Max limit of $150 when ARS is selected as offramping currency

## Notes
ARS icon - https://static.anclap.com/coin/ars.png

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/vortex/173?planning-poker) with Zenhub @ebma @Sharqiewicz @TorstenStueber @gianfra-t

**Comment by TorstenStueber** [comment]
This has been unblocked as ARS is now available on Nabla: https://github.com/pendulum-chain/tasks/issues/401#issuecomment-2412361777

**Comment by TorstenStueber** [comment]
I am closing this ticket as I merged it with https://github.com/pendulum-chain/vortex/issues/172.
