### ISSUE TITLE
Add rating component to vortex

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/vortex#182]
As a user i should be able to rate the Vortex dApp

## Acceptance criteria
* After successfully completing offramp on Vortex, show the rating pop-up
* The pop-up should close after rating is received.
* Once the rating is received from the user, they should not be prompted for rating for 15 days.
* If the user closes the pop-up without providing rating, show it after 15 days
* Following info to be captured in a excel file/database
    * Rating

## Note
* Linking the same design for Portal rating to avoid double work
* Replace the text "How would you rate our interface?" with "How would you rate your experience?"
* Show it at the bottom of the screen on the success screen
* This ticket is to capture the CSAT score of end users

## Design
https://www.figma.com/proto/5up5sghcttBogehUq4255i/App?node-id=2849-5156&t=t26OmPb2nSn7Axcj-0&scaling=scale-down&page-id=136%3A114&starting-point-node-id=2849%3A5156

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/vortex/182?planning-poker) with Zenhub @ebma @Sharqiewicz @TorstenStueber

**Comment by ebma** [comment]
We haven't implemented this in the portal yet, right? Can you still link to the respective issue ticket in the portal? Github will show the link in both tickets once you mention it here so it's easier to find, no matter where we end up implementing it first.

**Comment by ebma** [comment]
> Also let me know if anything unclear, also can we capture this in the same google sheet where we are dumping txns? maybe in the same doc but separate sheet?

Yes, we could dump it to the same overall document. However, we are already using two separate Google Sheets for storing the user email vs the transaction dump. So following that structure, we would actually need to create a third page. @pendulum-chain/devs any thoughts? Should we break the logic and add the user rating to the same doc or create a new one?

**Comment by gianfra-t** [comment]
@ebma I think we could in this case add it to the email sheet.

Btw, will we distinguish user by their wallet? Or by the local store. Because if it is wallet we could add the rating to the transaction spradsheet which already saves them.

**Comment by ebma** [comment]
I think we shouldn't add it to the same table as the transaction dump because then we'd need to retroactively find the row that belongs to the same transaction. Which shouldn't be too hard since we have all the information available but maybe we can keep it simple and without coupling. If we decide to update existing rows we might introduce bugs that mess up the existing data.

I would suggest we store a pair of `walletAddress + rating` in the sheet and add a timestamp that tracks the last user interaction with the rating (be it a dismissal of the dialog or an actual rating submission) to the localStorage.

**Comment by Sharqiewicz** [comment]
@ebma https://app.zenhub.com/workspaces/pendulum-6408a0365cda59c57d39bee5/issues/gh/pendulum-chain/portal/475

**Comment by Sharqiewicz** [comment]
@ebma https://github.com/pendulum-chain/portal/issues/475

**Comment by Sharqiewicz** [comment]
> I would suggest we store a pair of walletAddress + rating in the sheet and add a timestamp that tracks the last user interaction with the rating (be it a dismissal of the dialog or an actual rating submission) to the localStorage.

Good idea ✅

**Comment by gianfra-t** [comment]
> I would suggest we store a pair of walletAddress + rating in the sheet and add a timestamp that tracks the last user interaction with the rating (be it a dismissal of the dialog or an actual rating submission) to the localStorage.

Sounds good, let's do this in a different sheet then.

**Comment by Sharqiewicz** [comment]
@prayagd Can I pick it up?

**Comment by prayagd** [comment]
> I would suggest we store a pair of walletAddress + rating in the sheet and add a timestamp that tracks the last user interaction with the rating (be it a dismissal of the dialog or an actual rating submission) to the localStorage.

Like this idea

**Comment by prayagd** [comment]
@prayagd Can I pick it up?

Yes ser please, go ahead
