### ISSUE TITLE
Fix the telegram link on the Vortex status screens

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/vortex#188]
## Context 
Currently the link for telegram is expired, This ticket is to update it

## Todo
- Update the telegram link to this https://t.me/vortex_fi

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/vortex/188?planning-poker) with Zenhub @ebma @Sharqiewicz @TorstenStueber

**Comment by Sharqiewicz** [comment]
@prayagd Is it already done?

**Comment by ebma** [comment]
Yes, done. Closing this ticket.
