### ISSUE TITLE
Show message when redirected to Anchor website

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/vortex#190]
## Context
This ticket to show the end user a message that they are being redirected to the offramp website

## Requirements
* Once the user agrees on the quote
* Show a pop-up with the message "You are being redirected to the offramp page for next step"
* After showing this message redirect the user to the Anchor page
* Show this message for 3s before redirecting

**Comment by prayagd** [comment]
@vadaynujra should we also show a message if the user is first time and would need to KYC, something like this?
show message "You are being redirected to offramp page for KYC [Takes few minutes]. Please keep you documents ready"

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/vortex/190?planning-poker) with Zenhub @ebma @gianfra-t @Sharqiewicz @TorstenStueber

**Comment by ebma** [comment]
This could actually become tricky on mobile. AFAIK programmatically opening windows doesn't work too well on iOS if it doesn't follow an immediate user action. The 3-second delay makes it asynchronous which might not work properly on iOS.

**Comment by TorstenStueber** [comment]
@prayagd I don't think that we can implement it this way. We can't "redirect" (you mean opening a new tab) programmatically after three seconds. It needs to be done through an explicit click on a link by the user, otherwise many browsers will block this.

I feel like we might over engineer this for a prototype. We not just show some message directly above the button, should do the job.

**Comment by prayagd** [comment]
> @prayagd I don't think that we can implement it this way. We can't "redirect" (you mean opening a new tab) programmatically after three seconds.

@TorstenStueber so there is no way to introduce a timer saying redirecting in 5 4 3 2 1 and then redirect?

> I feel like we might over engineer this for a prototype. We not just show some message directly above the button, should do the job.

How would this look like?

**Comment by ebma** [comment]
> so there is no way to introduce a timer saying redirecting in 5 4 3 2 1 and then redirect?

No. At least not if we want to stay compatible with all browser and all platforms. It might work on some. 

> How would this look like?

"Clicking on 'Confirm' will lead you to the website of our partner for completing the next steps."?

**Comment by gianfra-t** [comment]
I guess as an alternative we could open a modal upon click of confirm, that shows something like "You will be redirected to the offramp page for next step", etc. Instead of open automatically, the user would need to confirm, again, on that modal.

**Comment by TorstenStueber** [comment]
Mhhh, actually we want to reduce the number of clicks instead of adding more clicks. Not sure whether this is the right strategy.

It's a balance we need to strike, though, as we also need to educate the user about the anchor UI and it could be a little overwhelming to show that text initially.

In unclear situations like this I would usually start with the simpler solution and that is to not add a modal/popup.

**Comment by prayagd** [comment]
Close this ticket

**Comment by gianfra-t** [comment]
I don't know if this is still relevant, but last week we were [testing](https://satoshipay.slack.com/archives/C0796MR8HED/p1728663604396829) the `window.open()` solution, and from that the conclusion is that this may be possible but with some caveats.

@prayagd in short, we could redirect to a new window, show a custom screen (for example, displaying the "redirected to the offramp...." message) and then set on that new window the anchor's page. But the problem still remains that we cannot show a message _after_ the user clicked and then, asynchronously, open the window.

**Comment by TorstenStueber** [comment]
Let's start with the simplest solution and make it more advanced when required and considered reasonable, shall we?

> Close this ticket
@prayagd what do you mean?
