### ISSUE TITLE
Fill the input field when clicked on balance

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/vortex#191]
## Context
This is ticket is fill the input field with the Available balance if the user clicks on the Available balance of the token they want to swap i.e USDC or USDC.e, currently they have to type that amount in the input field. 

## Requirement
* On clicking "Available" component the entire amount should get filled in the input field

## Technical Considerations
The available balance will have higher precision than two decimals. The value that will be plugged in should be rounded _down_ to two decimals from the precise available balance (this should already be the number shown).

## Note
For reference
<img width="778" alt="Screenshot 2024-10-07 at 11 01 08 AM" src="https://github.com/user-attachments/assets/8db70af4-fcec-4ce3-b1f9-cec8889a4f8e">

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/vortex/191?planning-poker) with Zenhub @ebma @gianfra-t @Sharqiewicz @TorstenStueber

**Comment by ebma** [comment]
Should we change the look of the 'Available: 0.38 USDC.e' text to indicate that it's clickable though?

**Comment by gianfra-t** [comment]
There is generally a "max" or "use max" button to the side of the balance to indicate this.

**Comment by TorstenStueber** [comment]
In Wise there is no max button but it is also displayed similarly to this ticket. The only difference is that the amount is underlined to indicate a clickable link (?).

**Comment by Sharqiewicz** [comment]
@TorstenStueber Great idea, we can underline it and change the color/weight

**Comment by prayagd** [comment]
> Should we change the look of the 'Available: 0.38 USDC.e' text to indicate that it's clickable though?

Yes, underline is the best solution for it. Which i see is already implemented
