### ISSUE TITLE
Update the progress screen text

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/vortex#192]
## Context
Currently on the progress screen, 
- the user is asked to not close the screen but it could be improved saying to leave the window open and check later
- the user is also shown the steps 1 to 11, which arent very helpful to the user. Instead we show a progress bar with %

## Requirement
* Update the text "Do not close this tab" to “Leave the window open and check back in 5 minutes”
* Remove the 1 to 11 steps and replace it with % bar
* As there are 11 steps, completion of each step should show a 9% increase on the loading bar (rounding off this number) reaching to 100%
* Show this bar below the text "Your transaction is in progress"
* (Torsten) I added more requirements [below](https://github.com/pendulum-chain/vortex/issues/192#issuecomment-2407145229)

## Note
For reference the screen to update text
<img width="280" alt="Screenshot 2024-10-07 at 11 52 45 AM" src="https://github.com/user-attachments/assets/7f0d6cde-9e98-4cc9-bd14-126f7c0bfcd7">

Loading bar for reference
<img width="230" alt="Screenshot 2024-10-10 at 11 08 05 AM" src="https://github.com/user-attachments/assets/959c1e07-9ba7-49dd-8d16-e2de71a6b8c2">

**Comment by prayagd** [comment]
@ebma @Sharqiewicz Would the loading bar reference would be enough to make the changes or would you need the design?

**Comment by ebma** [comment]
@prayagd what made you choose the reference loading bar? Is it because it is also able to show the steps with those pills? Is this important to you or would the progress bar that @Sharqiewicz shared also suffice?

**Comment by TorstenStueber** [comment]
> which arent very helpful to the user.

@prayagd Are you sure? We discussed this internally and there are different opinions. Where is this coming from?

**Comment by vadaynujra** [comment]
@TorstenStueber could you suggest predicted time for each step?

**Comment by TorstenStueber** [comment]
@prayagd Some questions about the new design. This is supposed to be a ring segment that grows from 0 degrees to 360 degress (representing 0% to 100% progress), correct? In the design the ring segment seems to start on the right and then grows clockwise. I would propose to let it start on the _top_ (and grow clockwise), as this is more common in my view.

## Growth behavior
For the behavior of the growth of the ring we decided the following:
* there are 12 equally spaced points on the ring (whereas the first and last point are at 0=360 degrees)
  * the first point is at 0 degrees and represents the initial state
  * each next point represents the completion of the next step (i.e., the point at 360/11 represents after step 1 has been completed
* the ring continuously advanced towards the next point by animation, the duration for this animation is the expected time for each step (I will provide times below)
* if the current step takes longer than this expected time, then the animation will just wait at the next point (which represents the completion of the current step) and will not move further along
* if the current step is faster than expected, then the ring will immediately jump to the point that represents the completion of the current step

## Texts
Contrary to the proposed design we decided to display a description of the current step below the ring (similar to how the steps are called right now).

**Comment by TorstenStueber** [comment]
Expected times:
* `prepareTransactions`: not relevant, will occur before the success screen starts
* `squidRouter`: not relevant, will occur before the success screen starts
* `pendulumFundEphemeral`: 80 seconds
* `executeXCM`: 40 seconds
* `subsidizePreSwap`: 24 seconds
* `nablaApprove`: 24 seconds
* `nablaSwap`: 24 seconds
* `subsidizePostSwap`: 24 seconds
* `executeSpacewalkRedeem`: 130 seconds
* `pendulumCleanup`: 6 seconds
* `stellarOfframp`: 6 seconds
* `stellarCleanup`: 6 seconds

**Comment by TorstenStueber** [comment]
@ebma It didn't take [a lot of extra work](https://github.com/pendulum-chain/vortex/pull/213/files).

However, you were right that I went overboard here. Just one timer for the whole offramp without splitting it into phases could have been enough.

I was just concerned that the user might run into an execution where everything takes a bit longer and then they would just wait for some long extra time although the percentage view already reached 100%. This is a bit confusing.

**Comment by vadaynujra** [comment]
@TorstenStueber is sharing the updated steps and the criteria for when they should be completed.

1. Bridging funds from Polygon --> Moonbeam - when the Moonbeam account has received the axlUSDC
2. Transferring XC from Moonbeam --> Pendulum - when the Pendulum ephemeral account has received the axlUSDC
3. Forex swap on Vortex DEX - when the Pendulum account has received the off-ramping asset
4. Bridging EURC to Stellar via Spacewalk - when the Stellar ephemeral account has received the off-ramping asset
5. Transferring to local partner for bank transfer - when the anchor's account has received the off-ramping asset. As soon as this shows as completed, user is taken to the transfer successful screen.

**Comment by ebma** [comment]
I don't understand the comment. Am I missing context? Is this supposed to replace the currently 12 phases that are shown on the progress screen and you want to reduce them to 5?
