### ISSUE TITLE
Add additional events to track on Vortex app

### ISSUE THREAD

**Issue by vadaynujra** [pendulum-chain/vortex#198]
### Context
After the first version of the tracking went live, we want to gain additional insights of the user behaviour during their journey.

### Requirement

- [ ] Track the following actions / events on Google Analytics:

1. User clicks 'Enter details' which opens MYKOBO journey
2. The 2 signatures are provided to the user - would tell us if both the signatures were triggered
3. The 2 signatures are signed by the user - would tell us if both the transactions were signed by the user (if it was shown to them)
4. The user is on the Progress page
5. Each step in the background - Would tell us where in the flow the user dropped / closed the tab (in case they do)
6. Submission of email on transaction successful screen
7. Submit email on transaction unsuccessful screen

- [ ] Suggest the events / parameters structure for the above

**Comment by vadaynujra** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/vortex/198?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by vadaynujra** [comment]
@ebma could you share how you have set up the events --> Param structure for the ones in the ticket?

**Comment by ebma** [comment]
Not sure what exactly you need but I'll give you some info and you can let me know what else you are interested in.

The structure of the code is the following
```
export interface TransactionEvent {
  event:
    | 'transaction_confirmation'
    | 'kyc_started'
    | 'kyc_completed'
    | 'signing_requested'
    | 'transactions_signed'
    | 'transaction_success'
    | 'transaction_failure';
  from_asset: string;
  to_asset: string;
  from_amount: string;
  to_amount: string;
}

export interface ProgressEvent {
  event: 'progress';
  phase: number;
}

export interface EmailSubmissionEvent {
  event: 'email_submission';
  transaction_status: 'success' | 'failure';
}
```

I translated this into the following structures in GTM, also see the PR https://github.com/pendulum-chain/vortex/pull/222. 

New Events

- GA4 Event | email_submission
- GA4 Event | signing_requested
- GA4 Event | transactions_signed
- GA4 Event | progress
- GA4 Event | kyc_started

New Triggers

- DL Event | email_submission
- DL Event | signing_requested
- DL Event | transactions_signed
- DL Event | progress
- DL Event | kyc_started

New Variables

- DLV | phase (used for tracking of the progress)
- DLV | transaction_status (used for tracking of the email submission)

So what's new is that there are a total of 5 new events, 3 of which (`kyc_started`, `signing_requested` and `transactions_signed`) are integrated into the group of events that come with the 4 attributes `from_asset, to_asset, from_amount, to_amount`. The `progress` event has a variable `phase` of type integer that will contain the phase that the user is currently in. And the `email_submission` event has a variable `transaction_status` that is either `success` of `failure` so we can distinguish if the user submitted the email from the success or the failure page.

**Comment by vadaynujra** [comment]
Looks good @ebma.

**Comment by vadaynujra** [comment]
@ebma for the phase variable, will it still follow the 12 steps we had defined? Do we have a reference for that anywhere now?

**Comment by ebma** [comment]
The definition is not that strict. I just defined it to be an integer. The range of steps depends on what we define in the prototype. So if at the moment we have 12 phases, it will trigger up to 12 times. If in the future we reduce it to 11 phases, then the events it will trigger 11 times, if we increase it to 13 phases it goes up to 13, etc.

**Comment by vadaynujra** [comment]
Depending on how many hops it requires to reach the Stellar off ramp, from the starting chain, this could vary and link different steps with the same integer, which would not be consistent. We might need the From and To currency attribute in the funnel view to get the required information via GA.

**Comment by TorstenStueber** [comment]
This becomes only relevant once we add other start ecosystems (Asset Hub), but we can of course already prepare this. Do you want to create a follow-up ticket for this @vadaynujra?
