### ISSUE TITLE
Add compare quote section

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/vortex#203]
As a vortex user, i should be able to see a quote comparison on vortex with Transak, Moonpay and Alchemypay

## Acceptance criteria
* On the vortex app UI once the user confirms show a new button "Compare fees" next to "Continue with Partner" similar to the wise reference attached
* Add text to the detail section "300 USDC is all you pay, fees included", the 300 USDC should be replaced as per the user input
* "Detail" text should be before the down arrow
* When clicked on "Compare fees" it should show similar to the wise reference text + table of quotes from competitors. Text provided in the notes
* Table reference also given below, Quotes from competitors should be fetched using
    * Transak - https://docs.transak.com/docs/query-parameters
    * Moonpay - https://dev.moonpay.com/reference/getsellquote
    * Alchemypay - https://alchemypay.readme.io/docs/price-query 
* Replace "No hidden fees" with "You could save upto 13.94 EUR" the 13.94 EUR should be calculated based on the (Vortex quote - Best quote from competitor)

## Notes
Text 
* Title - Save on exchange rate markups
* Body - 
The cost of your transfer comes from the fee and the exchange rate. Many providers offer “no fee”, while hiding a markup in the exchange rate, making you pay more.
At Vortex, we’ll never do that and show our fees upfront. 

## Icons
* Moonpay 
![image](https://github.com/user-attachments/assets/d857e160-bb4a-415c-96d1-6b7a1e448f94)
* Transak 
![image](https://github.com/user-attachments/assets/5ea7c972-7931-42db-bb07-088b83e7d99e)
* Alchemypay 
![image](https://github.com/user-attachments/assets/ab25a1e3-5869-4c47-9e3c-1bc4ec7c99a8)

## Design reference
<img width="597" alt="Screenshot 2024-10-25 at 5 35 35 PM" src="https://github.com/user-attachments/assets/a993738b-5eea-4a1a-b43b-b7fc4fff54c2">

Wise reference
 https://www.loom.com/share/ab28555da13f4376881cbfa2b4edefec?sid=5a9cc218-522f-4654-8cc0-0e9e3bec986e

Table reference  
<img width="382" alt="Screenshot 2024-10-25 at 5 43 14 PM" src="https://github.com/user-attachments/assets/7bf53071-2ab7-41c6-939d-7467fdf1a694">

**Comment by prayagd** [comment]
@prayagd will upload the designs

**Comment by prayagd** [comment]
@ebma @Sharqiewicz Please have a look at this ticket and let me know if any questions, also please add your estimates

**Comment by ebma** [comment]
@prayagd do we have an API key for transak? Otherwise we can't query the quote as far as I can tell.

**Comment by ebma** [comment]
We can't use Moonpay unfortunately. The only crypto currency they support is XLM on Stellar, see the list of currencies obtained from [here](https://dev.moonpay.com/reference/getcurrencies).
[moonpay_currencies.txt](https://github.com/user-attachments/files/17557746/moonpay_currencies.txt)

The `currencyCode` of the request needs to be of a cryptocurrency, so only XLM works for that query.
