### ISSUE TITLE
Suggest solution for anchor to identify Vortex transactions from others

### ISSUE THREAD

**Issue by vadaynujra** [pendulum-chain/vortex#215]
### Context
The off-ramp flow utilises the standard SEP 24 flow for off-ramping via Stellar anchors. To implement a specific (reduced) fee or limit (higher) for Vortex related off-ramping transactions, there must be a way for the anchor to identify Vortex related transactions on Stellar, from the rest (of the Stellar transactions). 

### To do

- [x] Suggest a solution for the above, that is also acceptable to the anchor
- [x] Document the solution on Notion

**Comment by prayagd** [comment]
Documented [here](https://www.notion.so/satoshipay/24-10-21-Anclap-Integration-1268b1b29b2f8040b775dcb46387c8fb?pvs=4). 
Closing the ticket
