### ISSUE TITLE
Grey out the output field

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/vortex#224]
## Context
Currently the output field on the vortex UI looks like its editable as it has the input field, this ticket is to fix that

## Requirement
* Remove the input field box from the output field
* Increase the font size of the output number and the currency shown

## Reference
![image](https://github.com/user-attachments/assets/0f233696-569a-4942-9d5b-f9e169174932)

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/vortex/224?planning-poker) with Zenhub @ebma @Sharqiewicz @TorstenStueber

**Comment by TorstenStueber** [comment]
@prayagd I can't access the screenshot.

**Comment by prayagd** [comment]
updated
