### ISSUE TITLE
Add client_domain to the information sent to the anchor

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/vortex#225]
### Context
In order to realise the terms of the agreement with anchors i.e. reduced fees, increased limits for off-ramp (and possibly more), there must be a way for the anchor to be able to identify transactions / users coming from Vortex.

Our client domain is `satoshipay.io`.

### Requirement

- [ ] Send the client signature with client_domain ID for SatoshiPay / Vortex to the anchors.

**Comment by gianfra-t** [comment]
Is this blocked until we get responses from Mykobo and Anclap? Or shall we explore this regardless.

**Comment by vadaynujra** [comment]
@gianfra-t from my understanding this has to be done for MYKOBO regardless. For Anclap it's dependent on them agreeing to it. Right @TorstenStueber ?

**Comment by ebma** [comment]
For the client_domain, we need to set up a stellar.toml with metadata about our organization, similar to what Mykobo did [here](https://circle.anchor.mykobo.co/.well-known/stellar.toml). I don't think we have that yet, at least I didn't find one on our validator [here](http://stellar-de-fra.satoshipay.io:11625/.well-known/stellar.toml).

The client domain is explained [here](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0010.md#verifying-the-client-domain). The structure of stellar.toml files is explained [here](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md) and the important field we need is the `SIGNING_KEY`. 

@pendulum-chain/product you can help us fill some of the fields already. It would be nice if you can think of what to put for the 'organization' parameters [here](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0001.md#organization-documentation). You can draw inspiration from what Mykobo does of course.

The protocol doesn't say which fields are obligatory and which are not but I think for the 'General information' it would be enough to have `VERSION`, `NETWORK_PASSPHRASE` and `SIGNING_KEY`.

**Comment by TorstenStueber** [comment]
We have a stellar.toml file, it is located at `https://satoshipay.io/.well-known/stellar.toml` and its content is:

```
VERSION="2.0.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
  "GBJQUIXUO4XSNPAUT6ODLZUJRV2NPXYASKUBY4G5MYP3M47PCVI55MNT",
  "GAK6Z5UVGUVSEK6PEOCAYJISTT5EJBB34PN3NOLEQG2SUKXRVV2F6HZY",
  "GC5SXLNAM3C4NMGK2PXK4R34B5GNZ47FYQ24ZIBFDFOCU6D4KBN4POAE"
]

[[VALIDATORS]]
ALIAS="spsingapore"
DISPLAY_NAME="SatoshiPay Singapore"
HOST="stellar-sg-sin.satoshipay.io:11625"
PUBLIC_KEY="GBJQUIXUO4XSNPAUT6ODLZUJRV2NPXYASKUBY4G5MYP3M47PCVI55MNT"
HISTORY="https://stellar-history-sg-sin.satoshipay.io/"

[[VALIDATORS]]
ALIAS="spiowa"
DISPLAY_NAME="SatoshiPay Iowa"
HOST="stellar-us-iowa.satoshipay.io:11625"
PUBLIC_KEY="GAK6Z5UVGUVSEK6PEOCAYJISTT5EJBB34PN3NOLEQG2SUKXRVV2F6HZY"
HISTORY="https://stellar-history-us-iowa.satoshipay.io/"

[[VALIDATORS]]
ALIAS="spfrankfurt"
DISPLAY_NAME="SatoshiPay Frankfurt"
HOST="stellar-de-fra.satoshipay.io:11625"
PUBLIC_KEY="GC5SXLNAM3C4NMGK2PXK4R34B5GNZ47FYQ24ZIBFDFOCU6D4KBN4POAE"
HISTORY="https://stellar-history-de-fra.satoshipay.io/"


[DOCUMENTATION]
ORG_NAME="SatoshiPay"
ORG_URL="https://satoshipay.io"
ORG_TWITTER="satoshipay"
ORG_GITHUB="satoshipay"
ORG_OFFICIAL_EMAIL="hello@satoshipay.io"

[[PRINCIPALS]]
name="Torsten Stüber"
email="torsten@satoshipay.io"
github="TorstenStueber"
twitter="torstenmove"
keybase="torstenstuber"
```

We can just easily add new entries to it.

**Comment by TorstenStueber** [comment]
I assume we can just create a new signing key randomly?

**Comment by ebma** [comment]
Ah perfect, thanks @TorstenStueber. So our `client_domain` would be `https://satoshipay.io/.well-known/stellar.toml` then. 

I also think it can be a random key. The account probably doesn't even need to exist. If I understood correctly, the secret of the `SIGNING_KEY` needs to be available to our clients for signing a message when initiating the SEP-10 authentication so the server can then use the public key we provide in the stellar.toml to verify that it's us.

**Comment by TorstenStueber** [comment]
I created a new key that we can use for the `SIGNING_KEY`: `GALH4RSM5UBEHHC5HIQ73FRXY6I4P6UMCQCWJF3S63N6RFGBBZG5QRZ3`.

**Comment by ebma** [comment]
Great. Now we need to change the implementation of the prototype to pass the `client_domain` field in the request to the web auth endpoint and sign the token with the signing key instead as is described [here](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0010.md#challenge). I suppose the implementation of this would still be a part of this ticket?

**Comment by TorstenStueber** [comment]
Yes, also my understanding of this ticket.

**Comment by gianfra-t** [comment]
PR [here](https://github.com/pendulum-chain/vortex/pull/236), we would need to:
- Add the key to the our `.toml`.
- Communicate to the anchor such that they whitelist us.

Also, I would like to explore [this](https://github.com/pendulum-chain/vortex/pull/236#issuecomment-2442456865) doubt I have before moving forward with the solution of the PR.

**Comment by vadaynujra** [comment]
@TorstenStueber @gianfra-t I included the client signature in addition to the client domain.

**Comment by TorstenStueber** [comment]
I just added the `SIGNING_KEY` to our stellar.toml file and also changed its `Content-Type` so that it can be viewed directly in the browser instead of being downloaded: https://satoshipay.io/.well-known/stellar.toml

**Comment by gianfra-t** [comment]
@pendulum-chain/product just FYI, the implementation is blocked until the Anchor whitelist us and we can test this.

**Comment by gianfra-t** [comment]
This is Anclap right? When they deploy it we can test it. Just to be sure, this is NOT the memo solution, just the acceptance of the `client_domain` signature. 
Do we expect any lower fee, customized UI, analytics? Or it would just be to test our implementation.

**Comment by TorstenStueber** [comment]
The point of this ticket is to just provide the client domain and the according signature. Any custom UI or fees is something to follow up later, not part of this ticket.

**Comment by gianfra-t** [comment]
I was asking to see if we should merge it or not quick, since the PR I'm working on for the memo will change the endpoint developed in this ticket. I will test it as soon as it works just please ping me.

**Comment by TorstenStueber** [comment]
It's good if we can deploy just the bare bones change (that just adds the client_domain and adds the necessary signature) asap because at least Mykobo is waiting for it. We can follow up with other changes later.

**Comment by gianfra-t** [comment]
I don't understand then. When I tested this with Mykobo, the sep-10 failed because of an unrecognized key.

**Comment by vadaynujra** [comment]
Please add estimates.

**Comment by TorstenStueber** [comment]
I updated the client domain in the ticket description to be `satoshipay.io`.

**Comment by prayagd** [comment]
@pendulum-chain/devs what the status here? i see succesful review, should we close?

**Comment by ebma** [comment]
Yes, I think this is done. Let's close.
