### ISSUE TITLE
Add support for new EVM chains to Vortex UI

### ISSUE THREAD

**Issue by vadaynujra** [pendulum-chain/vortex#226]
### User Story
As a user, I want to off ramp my USDC from the popular EVM chains.

### To do

- [ ]  Update the Vortex flow such that it starts the off-ramp from the following networks
    - [ ]  Ethereum
    - [ ]  BSC
    - [ ]  Arbitrum
    - [ ]  Base
    - [ ]  Avalanche 

### Acceptance Criteria

- Network dropdown allows user to choose network to off-ramp from
- Network selection creates a prompt for the user to change network in the wallet
- Asset list is specific to the network chosen
- Progress screen shows accurate asset and network
- Compare fee should consider accurate asset / network
- Changing network between EVM chains should not disconnect wallet considering wallet is connected

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/vortex/226?planning-poker) with Zenhub @ebma @gianfra-t @Sharqiewicz @TorstenStueber

**Comment by TorstenStueber** [comment]
> Network selection creates a prompt for the user to change network in the wallet

@pendulum-chain/product But this should only happen when the user did not already connect an EVM wallet yet, correct? I.e., when the user switches between EVM chains, then no wallet reconnect would be required.

> Asset list is specific to the network chosen

And what are the assets we want to support for each network? This is missing in the description. Shall we first investigate what network/asset pairs are supported by Squid Router?

**Comment by TorstenStueber** [comment]
@prayagd what is the difference between this ticket here and https://github.com/pendulum-chain/vortex/issues/292?

**Comment by prayagd** [comment]
> @prayagd what is the difference between this ticket here and https://github.com/pendulum-chain/vortex/issues/292?

That is more of a backend ticket, to take care of all things subsidy, squid router configuration etc etc, this is for the all the UI stuff

**Comment by ebma** [comment]
Wouldn't it make more sense to combine #292 and #226? #292 even mentions 

> Assumption: This ticket is for both frontend and backend changes, assuming configuration changes to the current setup

So let's just have all considerations grouped in one ticket (?)

**Comment by prayagd** [comment]
Based on the above suggestion, closing this ticket and moving all the changes to #292
