### ISSUE TITLE
BUG: On ramp failed before signing request

### ISSUE THREAD

**Issue by vadaynujra** [pendulum-chain/vortex#238]
### Steps to reproduce
1. Complete standard steps on anchor flow - MYKOBO UI
2. Come back to Vortex UI
3. Failed transaction shown -  no signing requests

Console log
![image](https://github.com/user-attachments/assets/09699187-da0d-4592-820d-4120b38c4ac8)

**Comment by TorstenStueber** [comment]
I found a few reports on wagmi directly, e.g., [this one from three weeks ago](https://github.com/wevm/wagmi/discussions/4325) or [this one from two year ago](https://github.com/wevm/wagmi/discussions/4216). However, there are no solutions in these two tickets.

We could add a work around and show a dedicated error message for this case, e.g., "Problem to connect with your wallet, ensure that it is working correctly."
