### ISSUE TITLE
Bug: set Forex AMM minimum output amount to lower number

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/vortex#240]
The Forex AMM swap operation takes an additional argument `_amountOutMin`, which determines that the swap operation should revert if the actually achieved output amount of the swap would drop below that value.

The usual idea is to get an upfront quote, subtract some slippage tolerance from that amount and use that as the `_amountOutMin` for the subsequent swap operation.

That's not what is happening in Vortex right now. The logic originates from the early prototype and the `_amountOutMin` used is just the quoted output amount rounded down to two decimals.

If the quote is fairly close to its rounded down value, then there is a high risk that due to price changes the actual swap that will take place a few minutes later will revert.

This means that the flow in this early version will not be recoverable as the transaction has been executed on chain and the account nonce already incremented. The swap transaction can therefore not be retried at a later point.

## TODO
* set the `_amountOutMin` to a much lower value, e.g., 5% below the original quote
* before submitting the Nabla swap transaction first request again the current quote and only submit the transaction if the quote only deviates at most 2% from the orginal quote, if not, then go to the failure screen but allow to retry
  * this way we can also try to recover manually at a later point

**Comment by prayagd** [comment]
@TorstenStueber what did we set here 2% or 5%?

**Comment by TorstenStueber** [comment]
I implemented both todos, so there is a 2% soft margin and a 5% hard margin.
