### ISSUE TITLE
Add Sentry

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/vortex#241]
In order to get some better understanding of common bugs, let's add Sentry (potentially only for some limited time).

The credentials are shared. The instructions can be found when logging in, there is an easy React integration. I think it is enough to add Sentry only to the frontend.

Sentry has an API that allows to log extra messages (`Sentry.captureMessage`) and we can use it to add a little bit of extra information, at least when switching to the next offramping phase.

## TODO
* integrate Sentry to the React frontend
* log extra information about phase changes (and maybe some other useful events that come to your mind)

**Comment by TorstenStueber** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/vortex/241?planning-poker) with Zenhub @gianfra-t @ebma @Sharqiewicz

**Comment by prayagd** [comment]
@TorstenStueber this is for the vortex UI?

**Comment by TorstenStueber** [comment]
@prayagd yes.
