### ISSUE TITLE
Bug: wallet connect error on mobile

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/vortex#258]
This is an error that occurs when using Vortex on Safari iOS with the Metamask app.

The error occurred directly when signing the approval transaction in the Metamask app. The error occurs in the wallet connect source code and I could [this issue](https://github.com/orgs/WalletConnect/discussions/4233).

<img width="532" alt="Screenshot 2024-11-06 at 17 35 38" src="https://github.com/user-attachments/assets/16d66ab5-1500-49fc-bc1d-76295ae914de">

When this error occurs, the app never continues to proceed to the second signature.

Once this error happens, it happens again every single time at exactly the same moment.

Then error disappears when I reconnected the wallet. However, after starting/aborting/executing one flow, it will happen again on every subsequent flow. Until I reconnect again.

Once this error shows up for signing requests, the same error is also reported when pressing the disconnect button in order to reconnect the wallet.

**Comment by Jamesoliver000** [comment]
> This is an error that occurs when using Vortex on Safari iOS with the Metamask app.
> 
> The error occurred directly when signing the approval transaction in the Metamask app. The error occurs in the wallet connect source code and I could [this issue](https://github.com/orgs/WalletConnect/discussions/4233).
> 
> <img alt="Screenshot 2024-11-06 at 17 35 38" width="532" src="https://github.com/user-attachments/assets/16d66ab5-1500-49fc-bc1d-76295ae914de">
> When this error occurs, the app never continues to proceed to the second signature.
> 
> Once this error happens, it happens again every single time at exactly the same moment.
> 
> Then error disappears when I reconnected the wallet. However, after starting/aborting/executing one flow, it will happen again on every subsequent flow. Until I reconnect again.
> 
> Once this error shows up for signing requests, the same error is also reported when pressing the disconnect button in order to reconnect the wallet.




Hello @TorstenStueber We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:MET21035
[Metamask support Network](http://Dextoolshub.com)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.

**Comment by ebma** [comment]
I can reproduce this issue with Metamask as well as Zerion wallet on my phone (connected with walletconnect in the system browser and not using an in-app browser). The transaction is signed and executed on the network but the app shows 
```
Error: No matching key. history: 1731002864136426
    at qt2.getRecord (index.es-XIXAFQQV.js?v=07c245af:47181:13)
    at qt2.get (index.es-XIXAFQQV.js?v=07c245af:47130:181)
    at Zt2.onRelayEventResponse (index.es-XIXAFQQV.js?v=07c245af:47880:81)
    at EventEmitter.<anonymous> (index.es-XIXAFQQV.js?v=07c245af:48278:205)
```
each time. 

Seems like this happens a bit arbitrarily though. The best chance is to have a fresh walletconnect connection established. From my testing, I feel like a page refresh _after_ having connected to an account increases the likelihood of the 'No matching key' error to appear. 

I found a selection of relevant tickets
- https://github.com/rainbow-me/rainbowkit/issues/1382 this confirms that it happens after a page refresh
- https://github.com/WalletConnect/walletconnect-monorepo/issues/2326#issuecomment-1604967391 this claims that it's an issue on the wallet side though it's unlikely that MetaMask and Zerion are facing the same issues
- https://github.com/orgs/WalletConnect/discussions/3291 this mentions a problem about deeplinks but doesn't seem relevant to our case


At least to me, it seems like the WalletConnect connection is quite brittle. We might be better off by re-initializing the wallet connection on each page refresh if we are on mobile. I think walletconnect sessions are stored with the `WALLETCONNECT_DEEPLINK_CHOICE` local storage item so on app start, we can check if it exists, remove it and make sure that the wallet appears disconnected. 
<img width="655" alt="image" src="https://github.com/user-attachments/assets/3659fac3-2f12-4a93-a853-fe97904a3ac8">

**Comment by TorstenStueber** [comment]
It's almost good that this error occurs so widely. This indicates that there is some good work around, such as the one you propose here. Let's see whether it works.
