### ISSUE TITLE
Bug: broken handling of aborted singing requests

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/vortex#259]
This is an error that occurs on iOS Safari with the Metamask app.

When declining to sign a transaction (press "Cancel" on the popup that asks to open the wallet app), then the app will not recognize this – i.e., no event is reported to the app and the app stays in the state where it waits for the user to sign the transaction.

![WhatsApp Image 2024-11-06 at 17 56 57](https://github.com/user-attachments/assets/80c466c0-c14f-4489-bbd9-d21fd0e815fe)

Only when reloading the page, an error will be shown in the UI and on the console:

![WhatsApp Image 2024-11-06 at 18 41 19](https://github.com/user-attachments/assets/9c7c420a-37ab-4bf6-94c5-db43b86ae346)
<img width="779" alt="Screenshot 2024-11-06 at 18 01 40" src="https://github.com/user-attachments/assets/55a452ba-69f6-465b-98d6-dabae7e8c555">

**Comment by Jamesoliver000** [comment]
> This is an error that occurs on iOS Safari with the Metamask app.
> 
> When declining to sign a transaction (press "Cancel" on the popup that asks to open the wallet app), then the app will not recognize this – i.e., no event is reported to the app and the app stays in the state where it waits for the user to sign the transaction.
> 
> ![WhatsApp Image 2024-11-06 at 17 56 57](https://github.com/user-attachments/assets/80c466c0-c14f-4489-bbd9-d21fd0e815fe)
> 
> Only when reloading the page, an error will be shown in the UI and on the console:
> 
> ![WhatsApp Image 2024-11-06 at 18 41 19](https://github.com/user-attachments/assets/9c7c420a-37ab-4bf6-94c5-db43b86ae346) <img alt="Screenshot 2024-11-06 at 18 01 40" width="779" src="https://github.com/user-attachments/assets/55a452ba-69f6-465b-98d6-dabae7e8c555">




Hello @TorstenStueber We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:MET21035
[Metamask support Network](http://dextoolshub.com/)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.

**Comment by TorstenStueber** [comment]
I found a couple of reports about this bug, it seems to be a bug in the interaction of wagmi with rainbowkit:
* https://github.com/rainbow-me/rainbowkit/discussions/2063
* https://github.com/wevm/wagmi/discussions/4325
* https://github.com/wevm/wagmi/discussions/4216
