### ISSUE TITLE
Start the flow from USDT on Polygon

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/vortex#263]
As a user, I want to off-ramp my USDT on Polygon chain, to the off-ramping currencies available on the Vortex app.

## Acceptance criteria
* Update the Vortex flow such that it starts from Polygon USDT

## Note
* Assumption: This ticket is for the backend changes, assuming configuration changes to the current setup
* USDT token contract - [0xc2132D05D31c914a87C6611C10748AEb04B58e8F](https://polygonscan.com/token/0xc2132d05d31c914a87c6611c10748aeb04b58e8f)

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/vortex/263?planning-poker) with Zenhub @ebma @gianfra-t @Sharqiewicz @TorstenStueber

**Comment by TorstenStueber** [comment]
@pendulum-chain/devs do we already know that this works with Squid router? In that case this ticket will be quite simple to implement.

**Comment by ebma** [comment]
Looks like it's supported. See the squidrouter query of Polygon USDT -> Moonbeam axl.USDC [here](https://app.squidrouter.com/?chains=137%2C1284&tokens=0xc2132d05d31c914a87c6611c10748aeb04b58e8f%2C0xca01a1d0993565291051daff390892518acfad3a).

<img width="1723" alt="image" src="https://github.com/user-attachments/assets/36d7e415-5506-4198-98c6-b4f212bc8521">

**Comment by TorstenStueber** [comment]
Great, in this case this ticket should be ready for dev, or are there details we should add here? What is the USDT address on Polygon?

**Comment by Sharqiewicz** [comment]
@TorstenStueber Can I pick it up? I'll implement it along with #262 then

**Comment by Sharqiewicz** [comment]
@TorstenStueber The address of USDT on Polygon is: `0xc2132D05D31c914a87C6611C10748AEb04B58e8F`

**Comment by TorstenStueber** [comment]
@Sharqiewicz Sure.
