### ISSUE TITLE
Text changes for ARS offramp 

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/vortex#264]
As a offramping user to ARS, i should be able to see the correct text across the Vortex app

## Acceptance criteria
* Replace EURC with ARS on the progress ticket for the following status messages
    * Swapping to EURC on Vortex DEX
    * Bridging EURC to Stellar via Spacewalk 
* Replace the following text
    * Funds will be received in 1 min(Instant SEPA) or 2 days(Standard SEPA). SEPA type dependent on the recipient bank support., with
    * Your funds will arrive in your bank account in a few minutes.

**Comment by prayagd** [comment]
text input to be received from the biz-dev team

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/vortex/264?planning-poker) with Zenhub @ebma @gianfra-t @Sharqiewicz @TorstenStueber

**Comment by TorstenStueber** [comment]
The first part will already happen automatically. Nothing to do.

For the second part, what to replace it with?

**Comment by prayagd** [comment]
Second part waiting from input from stakeholders will update once i get it

**Comment by TorstenStueber** [comment]
@prayagd did you get the input for the second part?

**Comment by prayagd** [comment]
@TorstenStueber already updated, hence removed the draft label

**Comment by gianfra-t** [comment]
The second part "Your funds will arrive in ....." must be shown only when ARS is offramped? or also changed for EURC?
