### ISSUE TITLE
Add url parameter to preselect output token

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/vortex#266]
In order to have efficient ad targeting, we the output token (and possibly input token) should be pre-selectable through url parameters.

## TODO
* upon startup, check whether there are url parameters `from` or `to`
  * if the url parameter `from` exists, then it will be one of the `InputTokenType` strings
    * if it is, then initially select that input token
  * if the url parameter `to` exists, then it will be one of the `OutputTokenType` strings
    * if it is, then initially select that output token
* if there are no parameters, then the default selection for the input token is `usdc`

**Comment by TorstenStueber** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/vortex/266?planning-poker) with Zenhub @ebma @gianfra-t @Sharqiewicz

**Comment by prayagd** [comment]
@vadaynujra added this to the Vortex enhancement's epic

**Comment by TorstenStueber** [comment]
@prayagd? I added it to the ARS one, it is particularly related to that.

**Comment by vadaynujra** [comment]
I agree that the need for this change only arises with this milestone and if possible, we should add to the ARS epic.
