### ISSUE TITLE
Support Polkadot wallet connect on Vortex

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/vortex#271]
### User Story
As a Vortex user, I want to be able to off ramp my USDC on Polkadot Asset Hub to the off-ramping currencies available on Vortex, and:
- I can connect my substrate wallet to the app
- The 'From' asset is preselected to USDC

## Acceptance criteria
When the user lands on "app.vortexfinance.co"
* Accepts Terms and Conditions
* Network preselected to Asset Hub - with an option to change to others
* Connect wallet opens up option to connect with substrate wallets

* The choice of network defines the Connect wallet options i.e. EVM or Substrate, and the options shown in the 'From' asset dropdown in the following way:

| Network     | Assets            | Wallet Options                           |
|-------------|--------------------|------------------------------------------|
| Asset Hub   | USDC              | Subwallet, Polkadot.js, Talisman, Nova   |
| Polygon     | USDC.e, USDC, USDT| Default with library                    |

* if the url query parameter "network" is given, use it to preselect a network (e.g., the strings `"assethub"` or `"polygon"`) – this should work similar to the https://github.com/pendulum-chain/vortex/issues/266
* store the selected network in the local storage
  * when the website and a network is already in the local storage, select that one and don't show the network selection popup
* For the substrate connect wallet use the logic from Portal with color and branding to be done as per the Vortex.

## Note
* If the user is connected to a substrate network and selects a EVM network from the network selector, disconnect the wallet connection, this does not apply if the user is connected to EVM network and selects other EVM network
* The network selector and filter of tokens is Zenlink reference, screenshot attached

## Reference
https://app.zenlink.pro/swap
<img width="1092" alt="Screenshot 2024-11-13 at 7 05 39 PM" src="https://github.com/user-attachments/assets/6bf7ea45-c939-4b0a-9041-467126b5d3d8">

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/vortex/271?planning-poker) with Zenhub @ebma @gianfra-t @Sharqiewicz @TorstenStueber

**Comment by prayagd** [comment]
@pendulum-chain/devs Let me know if any questions

**Comment by ebma** [comment]
I saw this ticket only after adding a comment to #272. I think this lacks the implications for the user experience. Similar to the question I put into the description of #272. How should we support both Polkadot and EVM wallets? What should the prototype show and how should it behave if a user connects to a Polkadot wallet?

**Comment by prayagd** [comment]
Updated the ticket, let me know if any confusion

**Comment by TorstenStueber** [comment]
The tickets in the BSC USDT epic does not define the network switcher yet. What is the relative priority of that epic to this one here (Asset Hub)?

If this one here comes first, then let's not refer to BSC yet. Then the main user facing definition of this ticket is to introduce a network switcher (the fact that we would need to have different wallet integrations is then implied and would also be a requirement of this ticket).

**Comment by vadaynujra** [comment]
Since the Binance USDT epic was picked up only as a fall back option, Asset Hub off ramp now holds higher relative priority between the 2 epics and should be progressed first, so that changes can be accommodated for the new EVM network (Binance) epic @TorstenStueber @prayagd

**Comment by Sharqiewicz** [comment]
For Polkadot-wallet connection we can use the logic from Portal. This is the `useConnectWallet` hook. We can then customize the appearance of Dialog ourselves - or we can also simply use https://github.com/TalismanSociety/talisman-connect

**Comment by TorstenStueber** [comment]
Yes, let's reuse the UX from the Portal.

**Comment by TorstenStueber** [comment]
I will remove any reference to BSC from the ticket description.

**Comment by TorstenStueber** [comment]
@pendulum-chain/product @pendulum-chain/devs shall we store the selected network in the local storage (similar to the token selection) so that the network selection popup doesn't show up on the next reload?

**Comment by ebma** [comment]
> shall we store the selected network in the local storage

Yes, let's do that.

**Comment by TorstenStueber** [comment]
Good, description added.

**Comment by Sharqiewicz** [comment]
@TorstenStueber Let's store it in the localStorage. Zenlink has the same solution

**Comment by prayagd** [comment]
@Sharqiewicz Updated the acceptance criteria, substrate connect wallet requirements
