### ISSUE TITLE
Add new events to google analytics

### ISSUE THREAD

**Issue by prayagd** [pendulum-chain/vortex#279]
## Context 
There are some new events that are missing for tracking, this ticket to implement those

## Requirement
* For the "to_amount" from the "transaction confirmation" event, currently captures the Forex AMM quote replace it with Final quote after fees. see reference
* Add one parameter to the "transaction failure" event, called "error_msg" which captures the error why the transaction failed
* Add one more event "compare_quote", when the user clicks on the "Compare fees" button
    * `from_asset`
    * `to_asset`
    * `from_amount`
    * `to_amount`
    * `transak_quote`
    * `moonpay_quote`
    * `alchempy_quote`

## Reference
![image](https://github.com/user-attachments/assets/67e10baf-9a28-46b3-812e-b566fb0841b5)

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/vortex/279?planning-poker) with Zenhub @ebma @gianfra-t @Sharqiewicz @TorstenStueber

**Comment by TorstenStueber** [comment]
> Add one more event "compare_quote", when the user clicks on the "Compare fees" button
So only on the press of the button, not when they change the input amount afterwards?

**Comment by prayagd** [comment]
FYI: Get agreement on the parameters mentioned above from the biz stakeholders
