### ISSUE TITLE
Add Asset Hub Flow

### ISSUE THREAD

**Issue by TorstenStueber** [pendulum-chain/vortex#283]
For offramping Asset Hub USDC, we need to implement a new flow structure that starts with the Asset Hub.

Different flow structures will also imply that other parts of the code are more generic, e.g., the `OfframpingState` type.

## Proposal
* for simplicity, we can just reuse the current definition of `OfframpingState` for the new flow
  * `squidRouterApproveHash`, `squidRouterSwapHash`, `moonbeamXcmTransactionHash` will not be required but they are defined as optional anyway
  * `squidRouterReceiverId` and `squidRouterReceiverHash` are determined in `constructInitialState` 
but we can keep this logic as we can use it to show a unique id to the user (https://github.com/pendulum-chain/vortex/issues/193)
* add a new field to `OfframpingState` that describes the type of flow (e.g., `"type": "evmMoonbeam" | "assetHub"`)
* add a new phase `assetHubXcm` and a handler
  * the handler will create an XCM transfer transaction the way it is defined [in this comment] (https://github.com/pendulum-chain/tasks/issues/427#issuecomment-2472873799) – i.e., leave `WeightLimit: Unlimited`
  * the handler will then use the Polkadot wallet integration to sign and submit this transaction
  * the handler will finally switch to the phase `subsidizePreSwap`
* remove the initial wait for the `squidRouterSwapHash` evm transaction from the `pendulumFundEphemeral` phase handler 
* in `prepareTransactions` phase handler proceed to
  * phase `squidRouter` if `state.type === "evmMoonbeam"`
  * phase `pendulumFundEphemeral` if `state.type === "assetHub"`
* in `pendulumFundEphemeral` phase handler proceed to
  * phase `executeXCM` if `state.type === "evmMoonbeam"`
  * phase `assetHubXcm` if `state.type === "assetHub"`

## Note
The new flow structure is not explicitly defined in the file `src/services/offrampingFlow.ts` but implicitly defined by the successor phase returned in every phase handler.

Whereas the initial structure of the evm-moonbeam flow is:
* `prepareTransactions`
* `squidRouter`
* `pendulumFundEphemeral`
* `executeXCM`
* `subsidizePreSwap`

the structure for the Asset Hub flow is:
* `prepareTransactions`
* `pendulumFundEphemeral`
* `assetHubXcm`
* `subsidizePreSwap`

**Comment by TorstenStueber** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/vortex/283?planning-poker) with Zenhub @ebma @gianfra-t @Sharqiewicz

**Comment by TorstenStueber** [comment]
To be discussed: how identify the Asset Hub user and derive the memo for sep10 (https://github.com/pendulum-chain/vortex/pull/257)

**Comment by ebma** [comment]
We can use the [same function](https://github.com/pendulum-chain/vortex/blob/cd844f1ca8d958175324805e8c8267a02d51f5fe/signer-service/src/api/services/sep10.service.js#L12) @gianfra-t implemented for the EVM accounts and just pass the Polkadot address. We need to make sure that we pass the addresses using the same ss58 encoding and we don't mix it up ending with different memos for the same account.

**Comment by TorstenStueber** [comment]
That makes sense, but I also meant the signing part. Do Polkadot wallets also have a standardized API to sign arbitrary messages? (I guess so, this happens on Polkassembly for example).

**Comment by gianfra-t** [comment]
I think so, we will use also the talisman package as in the portal right? In the only [example](https://www.npmjs.com/package/@talismn/connect-wallets) of the package they show a message sign.

**Comment by TorstenStueber** [comment]
I am not familiar with the Talisman package. That works with every Polkadot wallet, not just with Talisman?

**Comment by gianfra-t** [comment]
If I understand correctly, yes, it's our `wagmi` for Polkadot on the Portal.

**Comment by ebma** [comment]
Polkadot.js supports signing arbitrary messages, see the docs [here](https://polkadot.js.org/docs/keyring/start/sign-verify#using-known-pairs). As we can't do `const alice = keyring.addFromUri('//Alice');` but instead need to access the signer from the wallet, we can use talisman for that. But this is quite straightforward so once #271 is added and a polkadot signer is available, it's just a simple function call.
