### ISSUE TITLE
Add tweet carousel to Vortex home page

### ISSUE THREAD

**Issue by vadaynujra** [pendulum-chain/vortex#285]
### User Story
As a user, I want to be able to easily see the key media (tweets) related to Vortex on the home page and the major partners that vortex works with, so that I can trust the app when doing an off ramp. 

### To Do

- [x] Add 3 tweets on the vortex landing page
- [x] Add major partner logos under the trusted by section on the vortex landing page

### Acceptance Criteria

- Tweets should be constantly visible
- Add coming soon to Visa and Mastercard

**Comment by prayagd** [comment]
Closing this as this is done
