### ISSUE TITLE
Add a more robust fix for authCookie attributes.

### ISSUE THREAD

**Issue by gianfra-t** [pendulum-chain/vortex#297]
After the integration with ARS (#257) and the log in function, we are experiencing a bug on browser with strict privacy and security policies. 

On Firefox with strict settings, we see on the console after signing:

```
Cookie “authToken” has been rejected because it is foreign and does not have the “Partitioned“ attribute. [validate](https://prototype-signer-service-polygon-staging.pendulumchain.tech/v1/siwe/validate)

Cookie “authToken” has been rejected because it is foreign and does not have the “Partitioned“ attribute.
```

### Possible fixes:

- Try to set the Partitioned attribute (maybe not supported by express, has to be added manually in that case)
- Implement the solution suggested [here](https://github.com/pendulum-chain/vortex/pull/296#pullrequestreview-2454340447) and set again `SameSite=Strict,Lax`.

**Comment by TorstenStueber** [comment]
@pendulum-chain/product shall we add to the ARS epic and move to Ready?

**Comment by prayagd** [comment]
Moved to ready

**Comment by gianfra-t** [comment]
Yes totally, let's go with that one. After writing the issue I realized the Partitioned attribute may not be widely supported.
