### ISSUE TITLE
Update UI to include KYC flow for SEP31

### ISSUE THREAD

**Issue by vadaynujra** [pendulum-chain/vortex#313]
Add screens from SEP24 KYC flow
Consider open source library
Data required:
first_name: { type: 'string', description: 'Customer first name' },
  last_name: { type: 'string', description: 'Customer last name' },
  email_address: { type: 'string', description: 'Customer email address' },
  mobile_number: {
    type: 'string',
    description: 'Mobile phone number with country code, in E.164 format'
  },
  bank_account_number: {
    type: 'string',
    description: 'Customer IBAN number for SEPA transfers'
  },
  photo_id_front: {
    type: 'binary',
    description: 'Take a picture of the identification page of your passport.'
  },
  photo_proof_residence: {
    type: 'binary',
    description: 'Take a picture of your utility bill or bank statement.'
  },
  proof_of_liveness: {
    type: 'binary',
    description: 'Take a selfie with your face centered.'
  }
}

**Comment by prayagd** [comment]
Closing this ticket as MYKOBO has agreed to proceed with SEP-24 for which KYC capturing is not required on our end and would work as it was working earlier, we can re-open if something changes
